
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "db/migrate/*.rb"

Metrics/CyclomaticComplexity:
  Max: 10
